### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by QLaHPD** [PeterZhizhin/HSE-DeepLearning-NCSN#1]
What would be the necessary steps to train on a custom dataset?

**Comment by PeterZhizhin** [comment]
Hello, thank you very much for your question.

I didn't do it myself, but from what I understand, you would need to perform these steps:
1. Create a dataset class that is similar to other Torchvision datasets. See [this link](https://pytorch.org/docs/stable/torchvision/datasets.html) to read more about them. Also, see [this link](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html) for a tutorial. The dataset class needs to satisfy these conditions:
* The constructor should have this API: `__init__(root, train=True, transform=None, target_transform=None, download=False)`
* If your dataset doesn't have a target, then return anything as a target, the value will be ignored in the training loop.
* The dataset should have the `__len__` method that returns it's length.
* You should be able to construct a `DataLoader` from your dataset. 

2. Go to the main script `langevin_images.py` and add the dataset to [the parameters map](https://github.com/PeterZhizhin/HSE-DeepLearning-NCSN/blob/2cfeb286f10119a359a769ea3887e3314ea74163/langevin_images.py#L35). The map has these parameters: `constructor, number of channels (3 or 1), side length in pixels (28 for MNIST, 32 for CIFAR), base number of filters in the network (64 and 128 are used for MNIST and CIFAR)`.
3. Run the main script as described in the README file.

Hope this helps. Tell me if you have any problems.
